export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SEE_DATA = "SEE_DATA";
export const SEE_DATA_FAIL = "SEE_DATA_FAIL";

export const MAKE_RESERVATION = "MAKE_RESERVATION";
export const MAKE_RESERVATION_FAIL = "MAKE_RESERVATION_FAIL";

export const GET_RESERVATION_4_USER = "GET_RESERVATION_4_USER";
export const GET_RESERVATION_4_USER_FAIL = "GET_RESERVATION_4_USER_FAIL";

export const DECLINE_RESERVATION = "DECLINE_RESERVATION";
export const DECLINE_RESERVATION_FAIL = "DECLINE_RESERVATION_FAIL";

